[en]
  title = "Youhyun Kim"
  languageName = "English"
  weight = 1

  [en.params]
    displayName = "EN"
    isoCode = "en"
    rtl = false
    dateFormat = "2 January 2006"

  [en.author]
    name = "Youhyun Kim"
    image = "img/author.jpg"
    headline = "[Your Title/Role]"
    bio = "[Brief bio about yourself]"
    links = [
      { email = "mailto:your.email@example.com" },
      { link = "https://youhyunkim.com" },
      { github = "https://github.com/yourusername" },
      { linkedin = "https://linkedin.com/in/yourprofile" },
    ]