# Main menu
[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 30

[[main]]
  name = "Blog"
  pageRef = "/posts/"
  weight = 40

# Footer menu
[[footer]]
  name = "Privacy"
  pageRef = "/privacy/"
  weight = 10

[[footer]]
  name = "Contact"
  pageRef = "/contact/"
  weight = 20