baseURL = 'https://www.youhyunkim.com'
languageCode = 'en-us'
title = 'Youhyun Kim'
theme = 'PaperMod'

# Enable emoji support
enableEmoji = true
enableRobotsTXT = true

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 50

# Site parameters
[params]
  env = "production"
  description = "Youhyun Kim's personal website - Software developer, tech enthusiast, and lifelong learner"
  keywords = ["Youhyun Kim", "developer", "portfolio", "blog"]
  author = "Youhyun Kim"

  # Theme settings
  defaultTheme = "auto" # dark, light, auto
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Home page configuration
  [params.homeInfoParams]
    Title = "Hi there, I'm Youhyun Kim 👋"
    Content = """
Welcome to my personal website! I'm a passionate developer who loves building things and sharing knowledge.
Here you'll find my thoughts on technology, my latest projects, and insights from my journey in software development.

- 🔭 I'm currently working on [your current project]
- 🌱 I'm currently learning [what you're learning]
- 💬 Ask me about [your expertise areas]
- 📫 How to reach me: [your email]
    """

  # Social icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yourusername"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/yourprofile"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/yourusername"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:your.email@example.com"

  # Search functionality
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"

# Output formats for search
[outputs]
  home = ["HTML", "RSS", "JSON"]